Algoritmo "EXE procedimento 2"
// 
//  
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : 02/06/2021
Var
// Seção de Declarações das variáveis 
nome: caractere

procedimento name (x:caractere)
var
inicio

escreva ("bem vindo, ", x )
fimprocedimento

Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 

escreva ("digite seu nome: ")
leia (nome)
limpatela
name (nome)

Fimalgoritmo